phpmyadmin:
  name: phpmyadmin-web
  app: php-my-admin
  container: 
    name: php-my-admin
    image: phpmyadmin
phpmyadminservice:
  name: php-my-admin-service
  app: php-my-admin
  type: LoadBalancer
global:
  configmap:
    name: mysql-configmap
    database_url: mysql-service
  secret:
    name: mysql-secret
    type: Opaque
    username: BASE64Username
    password: BASE64Password