apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.app }}
    spec:
      containers:
      - name: {{ .Values.mysql.container.name }}
        image: {{ .Values.mysql.container.image }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password