apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlservice.name }}
spec:
  selector:
    app: {{ .Values.mysqlservice.app }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306